language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - nightly

matrix:
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install: travis_retry composer install

script:
  - vendor/bin/phpunit --filter testExample --coverage-clover coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)